import { Metadata } from "next";
import { ErrorWrapper } from "./error-wrapper";
import { ThemeProvider } from "./components/themeprovider";
import { ClerkProvider } from "@clerk/nextjs"
import { Navigation } from "./components/navigation";

export const metadata: Metadata = {
    title: {
        default: "Next.js Tutorial - Codevolution",
        template: "%s | Codevolution",
        absolute: ""
    },
    description: "Generated by Next.js",
};

export default function HomeLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="bg-[#374151]">
            <ClerkProvider>
                <ThemeProvider>
                    <body>
                        <ErrorWrapper>
                            <Navigation/>
                            {children}
                        </ErrorWrapper>
                    </body>
                </ThemeProvider>
            </ClerkProvider>
        </html>
    );
}