import { Metadata } from "next";
import { ErrorWrapper } from "./error-wrapper";
import { ThemeProvider } from "./components/themeprovider";

export const metadata: Metadata = {
    title: {
        default: "Next.js Tutorial - Codevolution",
        template: "%s | Codevolution",
        absolute: ""
    },
    description: "Generated by Next.js",
};

export default function HomeLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="bg-[#374151]">
            <ThemeProvider>
                <body>
                    <ErrorWrapper>
                        {children}
                    </ErrorWrapper>
                </body>
            </ThemeProvider>
        </html>
    );
}