import { Metadata } from "next";
import { ErrorWrapper } from "./error-wrapper";
import { ThemeProvider } from "./components/themeprovider";

export const metadata: Metadata = {
    title: {
        default: "Next.js Tutorial - Codevolution",
        template: "%s | Codevolution",
        absolute: ""
    },
    description: "Generated by Next.js",
};

export default function HomeLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <ThemeProvider>
                <body>
                    <header
                        style={{
                            backgroundColor: "lightblue",
                            padding: "1rem",
                        }}
                    >
                        <p>Header</p>
                    </header>
                    <ErrorWrapper>{children}</ErrorWrapper>
                    <footer
                        style={{
                            backgroundColor: "ghostwhite",
                            padding: "1rem",
                        }}
                    >
                        <p>Footer</p>
                    </footer>
                </body>
            </ThemeProvider>
        </html>
    );
}